name: Lint

on:
  schedule:
    - cron: "0 0 * * *" # At 00:00.
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  hadolint:
    name: Run hadolint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    strategy:
      matrix:
        package: [tf2-base, tf2-competitive, tf2-dm, tf2-mge, tf2-sourcemod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run hadolint on ${{ matrix.package }}
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./packages/${{ matrix.package }}/Dockerfile
          no-fail: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `
            #### Hadolint: \`${{ steps.hadolint.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
